from typing import Protocol

from .models import AlgorithmInstance, ContainerSpec


class InstanceRepository(Protocol):
    def list(self) -> list[AlgorithmInstance]: ...

    def get(self, instance_id: str) -> AlgorithmInstance | None: ...

    def find_by_algorithm(self, algorithm_version_id: str) -> AlgorithmInstance | None: ...

    def find_all_by_algorithm(self, algorithm_version_id: str) -> list[AlgorithmInstance]: ...

    def save(self, instance: AlgorithmInstance) -> None: ...

    def delete(self, instance_id: str) -> None: ...


class ContainerRuntime(Protocol):
    def discover(self) -> list[AlgorithmInstance]: ...

    def create(self, spec: ContainerSpec) -> tuple[str, str]: ...

    def start(self, instance_id: str) -> None: ...

    def stop(self, instance_id: str) -> None: ...

    def remove(self, instance_id: str) -> None: ...

    def is_healthy(self, instance: AlgorithmInstance) -> bool: ...

    def probe_health(self, instance: AlgorithmInstance) -> bool: ...

    def list_gpus(self) -> list[dict[str, object]]: ...

    def logs(self, instance_id: str, tail: int = 200) -> list[str]: ...
