from typing import Protocol
from uuid import UUID

from .entities import AlgorithmVersion, BuildJob


class AlgorithmRepository(Protocol):
    def add(self, algorithm: AlgorithmVersion) -> None: ...

    def list(self) -> list[AlgorithmVersion]: ...

    def get(self, algorithm_id: UUID) -> AlgorithmVersion | None: ...

    def find_version(self, key: str, version: str) -> AlgorithmVersion | None: ...

    def save(self, algorithm: AlgorithmVersion) -> None: ...

    def delete(self, algorithm_id: UUID) -> None: ...


class BuildJobRepository(Protocol):
    def add(self, job: BuildJob) -> None: ...

    def save(self, job: BuildJob) -> None: ...

    def get(self, job_id: UUID) -> BuildJob | None: ...
