from typing import Protocol

from .models import RuntimeInstance, RuntimeRequest


class AlgorithmManagerGateway(Protocol):
    def list_instances(self) -> list[RuntimeInstance]: ...

    def ensure_running(self, request: RuntimeRequest) -> RuntimeInstance: ...

    def ensure_replicas(
        self, request: RuntimeRequest, replicas: int
    ) -> list[RuntimeInstance]: ...

    def stop(self, instance_id: str) -> RuntimeInstance: ...

    def remove(self, instance_id: str) -> None: ...

    def logs(self, instance_id: str, tail: int = 200) -> list[str]: ...

    def list_gpus(self) -> list[dict[str, object]]: ...

    def touch(self, instance_id: str) -> RuntimeInstance: ...
